INSERT INTO `fcs` (`codigo`, `nombre`) VALUES
('CEG', 'Centro de Estudios Generales'),
('FFL', 'Facultad de Filosofía y Letras'),
('FCS', 'Facultad de Ciencias Sociales'),
('FCEN', 'Facultad de Ciencias Exactas y Naturales'),
('FCTM', 'Facultad de Ciencias de la Tierra y el Mar'),
('FCSA', 'Facultad de Ciencias de la Salud'),
('CIDE', 'Centro de Investigación y la Docencia en Educación'),
('CIDEA', 'Centro de Investigación, Docencia y Extensión Artística');

INSERT INTO `unidadacademica` (`codigoU`,`nombre`,`fcs_codigo`) VALUES
('ELCL','Escuela de Literatura y Ciencias del Lenguaje',2),
('AESP',' Área de Español',2),
('AFR','Área de Francés',2),
('AING','Área de Inglés',2),
('EECR','Escuela de Ecuménicas y Ciencias de la Religión',2),
('IDELA','Instituto de Estudios Latinoamericanos',2),
('EF','Escuela de Filosofía',2),
('EBDI','Escuela de Bibliotecología, Documentación e Información',2),
('IEM','Instituto de Estudios de la Mujer',2),
('EH','Escuela de Historia',3),
('ES',' Escuela de Sociología',3),
('EPPS','Escuela de Planificación y Promoción Social',3),
('EDA','Escuela de Administración',3),
('ESP','Escuela de Secretariado Profesional',3),
('ERI','Escuela de Relaciones Internacionales',3),
('EE','Escuela de Economía',3),
('CINPE','Centro Internacional de Política Económica para el Desarrollo Sostenible',3),
('EPS','Escuela de Psicología',3),
('EM','Escuela de Matemática',4),
('ECB','Escuela de Ciencias Biológicas',4),
('EQ','Escuela de Química',4),
('ETCG','Escuela de Topografía, Catastro y Geodesia',4),
('EI','Escuela de Informática',4),
('PROCMAR','Programa de Maestría en Ciencias Marinas y Costeras',4),
('DF','Departamento de Física',4),
('ProGesTic','Posgrado en Gestión de la Tecnología de Información y Comunicación',4),
('ECG','Escuela de Ciencias Geográficas',5),
('ECA','Escuela de Ciencias Agrarias',5),
('ICOMVIS','Instituto de Conservación y Vida Silvestre',5),
('EDECA','Escuela de Ciencias Ambientales',5),
('CINAT','Centro de Investigaciones Apícolas Tropicales',5),
('IRET',' Instituto Regional de Estudios en Sustancias Tóxicas',5),
('INISEFOR','Instituto de Investigación y Servicios Forestales',5),
('EMV','Escuela de Medicina Veterinaria',6),
('PCVET','Programa Regional de Posgrado en Ciencias Veterinarias Tropicales',6),
('CIEMHCAVI','Escuela de Ciencias del Deporte y el Movimiento Humano y Calidad de Vida',6),
('DEB','División de Educación Básica',7),
('DET',' División de Educación para el trabajo',7),
('DER','División de Educación Rural',7),
('DED','División de Educología',7),
('EAE','Escuela de Arte Escénico',8),
('EACV','Escuela de Arte y Comunicación Visual',8),
('ED','Escuela de Danza',8),
('EMU','Escuela de Música',8);
