/*
-- Query: SELECT * FROM sigpe_test.unidadacademica
LIMIT 0, 1000

-- Date: 2019-10-07 15:38
*/
INSERT INTO `unidadacademica` (`id_unidad`,`codigoU`,`nombre`,`subunidad`,`fcs_codigo`,`telefono1`,`telefono2`,`pag_web`,`email`,`descripcion`,`imagen`) VALUES (1,'ELCL','Escuela de Literatura y Ciencias del Lenguaje',NULL,2,'-',NULL,'-','-','-','-');
INSERT INTO `unidadacademica` (`id_unidad`,`codigoU`,`nombre`,`subunidad`,`fcs_codigo`,`telefono1`,`telefono2`,`pag_web`,`email`,`descripcion`,`imagen`) VALUES (2,'AESP','Área de Español',NULL,2,'-',NULL,'-','-','-','-');
INSERT INTO `unidadacademica` (`id_unidad`,`codigoU`,`nombre`,`subunidad`,`fcs_codigo`,`telefono1`,`telefono2`,`pag_web`,`email`,`descripcion`,`imagen`) VALUES (3,'AFR','Área de Francés',NULL,2,'-',NULL,'-','-','-','-');
INSERT INTO `unidadacademica` (`id_unidad`,`codigoU`,`nombre`,`subunidad`,`fcs_codigo`,`telefono1`,`telefono2`,`pag_web`,`email`,`descripcion`,`imagen`) VALUES (4,'AING','Área de Inglés',NULL,2,'-',NULL,'-','-','-','-');
INSERT INTO `unidadacademica` (`id_unidad`,`codigoU`,`nombre`,`subunidad`,`fcs_codigo`,`telefono1`,`telefono2`,`pag_web`,`email`,`descripcion`,`imagen`) VALUES (5,'EECR','Escuela de Ecuménicas y Ciencias de la Religión',NULL,2,'-',NULL,'-','-','-','-');
INSERT INTO `unidadacademica` (`id_unidad`,`codigoU`,`nombre`,`subunidad`,`fcs_codigo`,`telefono1`,`telefono2`,`pag_web`,`email`,`descripcion`,`imagen`) VALUES (6,'IDELA','Instituto de Estudios Latinoamericanos',NULL,2,'-',NULL,'-','-','-','-');
INSERT INTO `unidadacademica` (`id_unidad`,`codigoU`,`nombre`,`subunidad`,`fcs_codigo`,`telefono1`,`telefono2`,`pag_web`,`email`,`descripcion`,`imagen`) VALUES (7,'EF','Escuela de Filosofía',NULL,2,'-',NULL,'-','-','-','-');
INSERT INTO `unidadacademica` (`id_unidad`,`codigoU`,`nombre`,`subunidad`,`fcs_codigo`,`telefono1`,`telefono2`,`pag_web`,`email`,`descripcion`,`imagen`) VALUES (8,'EBDI','Escuela de Bibliotecología, Documentación e Información',NULL,2,'-',NULL,'-','-','-','-');
INSERT INTO `unidadacademica` (`id_unidad`,`codigoU`,`nombre`,`subunidad`,`fcs_codigo`,`telefono1`,`telefono2`,`pag_web`,`email`,`descripcion`,`imagen`) VALUES (9,'IEM','Instituto de Estudios de la Mujer',NULL,2,'-',NULL,'-','-','-','-');
INSERT INTO `unidadacademica` (`id_unidad`,`codigoU`,`nombre`,`subunidad`,`fcs_codigo`,`telefono1`,`telefono2`,`pag_web`,`email`,`descripcion`,`imagen`) VALUES (10,'EH','Escuela de Historia',NULL,3,'-',NULL,'-','-','-','-');
INSERT INTO `unidadacademica` (`id_unidad`,`codigoU`,`nombre`,`subunidad`,`fcs_codigo`,`telefono1`,`telefono2`,`pag_web`,`email`,`descripcion`,`imagen`) VALUES (11,'ES','Escuela de Sociología',NULL,3,'-',NULL,'-','-','-','-');
INSERT INTO `unidadacademica` (`id_unidad`,`codigoU`,`nombre`,`subunidad`,`fcs_codigo`,`telefono1`,`telefono2`,`pag_web`,`email`,`descripcion`,`imagen`) VALUES (12,'EPPS','Escuela de Planificación y Promoción Social',NULL,3,'-',NULL,'-','-','-','-');
INSERT INTO `unidadacademica` (`id_unidad`,`codigoU`,`nombre`,`subunidad`,`fcs_codigo`,`telefono1`,`telefono2`,`pag_web`,`email`,`descripcion`,`imagen`) VALUES (13,'EDA','Escuela de Administración',NULL,3,'-',NULL,'-','-','-','-');
INSERT INTO `unidadacademica` (`id_unidad`,`codigoU`,`nombre`,`subunidad`,`fcs_codigo`,`telefono1`,`telefono2`,`pag_web`,`email`,`descripcion`,`imagen`) VALUES (14,'ESP','Escuela de Secretariado Profesional',NULL,3,'-',NULL,'-','-','-','-');
INSERT INTO `unidadacademica` (`id_unidad`,`codigoU`,`nombre`,`subunidad`,`fcs_codigo`,`telefono1`,`telefono2`,`pag_web`,`email`,`descripcion`,`imagen`) VALUES (15,'ERI','Escuela de Relaciones Internacionales',NULL,3,'-',NULL,'-','-','-','-');
INSERT INTO `unidadacademica` (`id_unidad`,`codigoU`,`nombre`,`subunidad`,`fcs_codigo`,`telefono1`,`telefono2`,`pag_web`,`email`,`descripcion`,`imagen`) VALUES (16,'EE','Escuela de Economía',NULL,3,'-',NULL,'-','-','-','-');
INSERT INTO `unidadacademica` (`id_unidad`,`codigoU`,`nombre`,`subunidad`,`fcs_codigo`,`telefono1`,`telefono2`,`pag_web`,`email`,`descripcion`,`imagen`) VALUES (17,'CINPE','Centro Internacional de Política Económica para el Desarrollo Sostenible',NULL,3,'-',NULL,'-','-','-','-');
INSERT INTO `unidadacademica` (`id_unidad`,`codigoU`,`nombre`,`subunidad`,`fcs_codigo`,`telefono1`,`telefono2`,`pag_web`,`email`,`descripcion`,`imagen`) VALUES (18,'EPS','Escuela de Psicología',NULL,3,'-',NULL,'-','-','-','-');
INSERT INTO `unidadacademica` (`id_unidad`,`codigoU`,`nombre`,`subunidad`,`fcs_codigo`,`telefono1`,`telefono2`,`pag_web`,`email`,`descripcion`,`imagen`) VALUES (19,'EM','Escuela de Matemática',NULL,4,'-',NULL,'-','-','-','-');
INSERT INTO `unidadacademica` (`id_unidad`,`codigoU`,`nombre`,`subunidad`,`fcs_codigo`,`telefono1`,`telefono2`,`pag_web`,`email`,`descripcion`,`imagen`) VALUES (20,'ECB','Escuela de Ciencias Biológicas',NULL,4,'-',NULL,'-','-','-','-');
INSERT INTO `unidadacademica` (`id_unidad`,`codigoU`,`nombre`,`subunidad`,`fcs_codigo`,`telefono1`,`telefono2`,`pag_web`,`email`,`descripcion`,`imagen`) VALUES (21,'EQ','Escuela de Química',NULL,4,'-',NULL,'-','-','-','-');
INSERT INTO `unidadacademica` (`id_unidad`,`codigoU`,`nombre`,`subunidad`,`fcs_codigo`,`telefono1`,`telefono2`,`pag_web`,`email`,`descripcion`,`imagen`) VALUES (22,'ETCG','Escuela de Topografía, Catastro y Geodesia',NULL,4,'-',NULL,'-','-','-','-');
INSERT INTO `unidadacademica` (`id_unidad`,`codigoU`,`nombre`,`subunidad`,`fcs_codigo`,`telefono1`,`telefono2`,`pag_web`,`email`,`descripcion`,`imagen`) VALUES (23,'EI','Escuela de Informática',NULL,4,'25255858','26965896','www.escinf.una.ac.cr','escinf@una.cr','-','uploads/unidadesAcademicas/curso2.jpg');
INSERT INTO `unidadacademica` (`id_unidad`,`codigoU`,`nombre`,`subunidad`,`fcs_codigo`,`telefono1`,`telefono2`,`pag_web`,`email`,`descripcion`,`imagen`) VALUES (24,'PROCMAR','Programa de Maestría en Ciencias Marinas y Costeras',NULL,4,'-',NULL,'-','-','-','-');
INSERT INTO `unidadacademica` (`id_unidad`,`codigoU`,`nombre`,`subunidad`,`fcs_codigo`,`telefono1`,`telefono2`,`pag_web`,`email`,`descripcion`,`imagen`) VALUES (25,'DF','Departamento de Física',NULL,4,'-',NULL,'-','-','-','-');
INSERT INTO `unidadacademica` (`id_unidad`,`codigoU`,`nombre`,`subunidad`,`fcs_codigo`,`telefono1`,`telefono2`,`pag_web`,`email`,`descripcion`,`imagen`) VALUES (26,'ProGesTic','Posgrado en Gestión de la Tecnología de Información y Comunicación',NULL,4,'-',NULL,'-','-','-','-');
INSERT INTO `unidadacademica` (`id_unidad`,`codigoU`,`nombre`,`subunidad`,`fcs_codigo`,`telefono1`,`telefono2`,`pag_web`,`email`,`descripcion`,`imagen`) VALUES (27,'ECG','Escuela de Ciencias Geográficas',NULL,5,'-',NULL,'-','-','-','-');
INSERT INTO `unidadacademica` (`id_unidad`,`codigoU`,`nombre`,`subunidad`,`fcs_codigo`,`telefono1`,`telefono2`,`pag_web`,`email`,`descripcion`,`imagen`) VALUES (28,'ECA','Escuela de Ciencias Agrarias',NULL,5,'-',NULL,'-','-','-','-');
INSERT INTO `unidadacademica` (`id_unidad`,`codigoU`,`nombre`,`subunidad`,`fcs_codigo`,`telefono1`,`telefono2`,`pag_web`,`email`,`descripcion`,`imagen`) VALUES (29,'ICOMVIS','Instituto de Conservación y Vida Silvestre',NULL,5,'-',NULL,'-','-','-','-');
INSERT INTO `unidadacademica` (`id_unidad`,`codigoU`,`nombre`,`subunidad`,`fcs_codigo`,`telefono1`,`telefono2`,`pag_web`,`email`,`descripcion`,`imagen`) VALUES (30,'EDECA','Escuela de Ciencias Ambientales',NULL,5,'-',NULL,'-','-','-','-');
INSERT INTO `unidadacademica` (`id_unidad`,`codigoU`,`nombre`,`subunidad`,`fcs_codigo`,`telefono1`,`telefono2`,`pag_web`,`email`,`descripcion`,`imagen`) VALUES (31,'CINAT','Centro de Investigaciones Apícolas Tropicales',NULL,5,'-',NULL,'-','-','-','-');
INSERT INTO `unidadacademica` (`id_unidad`,`codigoU`,`nombre`,`subunidad`,`fcs_codigo`,`telefono1`,`telefono2`,`pag_web`,`email`,`descripcion`,`imagen`) VALUES (32,'IRET','Instituto Regional de Estudios en Sustancias Tóxicas',NULL,5,'-',NULL,'-','-','-','-');
INSERT INTO `unidadacademica` (`id_unidad`,`codigoU`,`nombre`,`subunidad`,`fcs_codigo`,`telefono1`,`telefono2`,`pag_web`,`email`,`descripcion`,`imagen`) VALUES (33,'INISEFOR','Instituto de Investigación y Servicios Forestales',NULL,5,'-',NULL,'-','-','-','-');
INSERT INTO `unidadacademica` (`id_unidad`,`codigoU`,`nombre`,`subunidad`,`fcs_codigo`,`telefono1`,`telefono2`,`pag_web`,`email`,`descripcion`,`imagen`) VALUES (34,'EMV','Escuela de Medicina Veterinaria',NULL,6,'-',NULL,'-','-','-','-');
INSERT INTO `unidadacademica` (`id_unidad`,`codigoU`,`nombre`,`subunidad`,`fcs_codigo`,`telefono1`,`telefono2`,`pag_web`,`email`,`descripcion`,`imagen`) VALUES (35,'PCVET','Programa Regional de Posgrado en Ciencias Veterinarias Tropicales','Escuela de Medicina Veterinaria',6,'-',NULL,'-','-','-','-');
INSERT INTO `unidadacademica` (`id_unidad`,`codigoU`,`nombre`,`subunidad`,`fcs_codigo`,`telefono1`,`telefono2`,`pag_web`,`email`,`descripcion`,`imagen`) VALUES (36,'CIEMHCAVI','Escuela de Ciencias del Deporte y el Movimiento Humano y Calidad de Vida',NULL,6,'-',NULL,'-','-','-','-');
INSERT INTO `unidadacademica` (`id_unidad`,`codigoU`,`nombre`,`subunidad`,`fcs_codigo`,`telefono1`,`telefono2`,`pag_web`,`email`,`descripcion`,`imagen`) VALUES (37,'DEB','División de Educación Básica',NULL,7,'-',NULL,'-','-','-','-');
INSERT INTO `unidadacademica` (`id_unidad`,`codigoU`,`nombre`,`subunidad`,`fcs_codigo`,`telefono1`,`telefono2`,`pag_web`,`email`,`descripcion`,`imagen`) VALUES (38,'DET','División de Educación para el trabajo',NULL,7,'-',NULL,'-','-','-','-');
INSERT INTO `unidadacademica` (`id_unidad`,`codigoU`,`nombre`,`subunidad`,`fcs_codigo`,`telefono1`,`telefono2`,`pag_web`,`email`,`descripcion`,`imagen`) VALUES (39,'DER','División de Educación Rural',NULL,7,'-',NULL,'-','-','-','-');
INSERT INTO `unidadacademica` (`id_unidad`,`codigoU`,`nombre`,`subunidad`,`fcs_codigo`,`telefono1`,`telefono2`,`pag_web`,`email`,`descripcion`,`imagen`) VALUES (40,'DED','División de Educología',NULL,7,'-',NULL,'-','-','-','-');
INSERT INTO `unidadacademica` (`id_unidad`,`codigoU`,`nombre`,`subunidad`,`fcs_codigo`,`telefono1`,`telefono2`,`pag_web`,`email`,`descripcion`,`imagen`) VALUES (41,'EAE','Escuela de Arte Escénico',NULL,8,'-',NULL,'-','-','-','-');
INSERT INTO `unidadacademica` (`id_unidad`,`codigoU`,`nombre`,`subunidad`,`fcs_codigo`,`telefono1`,`telefono2`,`pag_web`,`email`,`descripcion`,`imagen`) VALUES (42,'EACV','Escuela de Arte y Comunicación Visual',NULL,8,'-',NULL,'-','-','-','-');
INSERT INTO `unidadacademica` (`id_unidad`,`codigoU`,`nombre`,`subunidad`,`fcs_codigo`,`telefono1`,`telefono2`,`pag_web`,`email`,`descripcion`,`imagen`) VALUES (43,'ED','Escuela de Danza',NULL,8,'-',NULL,'-','-','-','-');
INSERT INTO `unidadacademica` (`id_unidad`,`codigoU`,`nombre`,`subunidad`,`fcs_codigo`,`telefono1`,`telefono2`,`pag_web`,`email`,`descripcion`,`imagen`) VALUES (44,'EMU','Escuela de Música',NULL,8,'-',NULL,'-','-','-','-');
